<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Publication group</name>
   <tag></tag>
   <elementGuidId>afe90d6f-7209-4b35-8a2b-3b45024ed33d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>38px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eNQAEJ sc-fhYwyz fsejco sc-kgoBCf dbGXzI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-htpNat sc-bxivhb sc-jzJRlG gYHZYm&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb QuLXz&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb bdIdfB&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb sc-jzJRlG sc-cHGsZl towlb&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb sc-jzJRlG sc-gJWqzi cKgwXb&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb sc-jzJRlG sc-cJSrbW sc-bMvGRv iBdQjw&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb hMKCoL&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb chxSGy&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb sc-jzJRlG joQxRn&quot;]/div[@class=&quot;sc-htpNat sc-bxivhb sc-jzJRlG fBkzSC&quot;]/button[@class=&quot;sc-eNQAEJ sc-fhYwyz fsejco sc-kgoBCf dbGXzI&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>(//button[@type='button'])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div[3]/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publication group'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single publication'])[1]/following::button[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Want more features?'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
